### ISSUE TITLE
Revise git example using markdown

### ISSUE THREAD

**Issue by hirja** [MAustin428/agile_5e#4]
The git example that Jake added is in an unstructured, unprofessional .txt file that isn't easily tracked or modified. We should create a `docs` directory (or similar) in the repository's root directory to house documentation like this. We should also convert the git example documentation to markdown.

This revision is not expected to impact functionality. Documentation would be collected and moved into a shared location. The format of some documentation might change, but the content would largely remain the same.

**Comment by mendonk** [comment]
@hirja @MAustin428 I'm on it

**Comment by hirja** [comment]
@mendonk Thanks
