### ISSUE TITLE
Organize Thurs Meeting

### ISSUE THREAD

**Issue by MAustin428** [MAustin428/agile_5e#5]
Hirja will schedule a technical design session for Thurs, 07-Jan. The goal of this meeting will be to formalize a document which outlines the technical specifications for the project.

**Comment by hirja** [comment]
@MAustin428 @mendonk How about 730pm on 1/7/21?

**Comment by mendonk** [comment]
@MAustin428 @hirja  I'm in.

**Comment by MAustin428** [comment]
> 
> 
> @MAustin428 @mendonk How about 730pm on 1/7/21?


[calendar.google.com/MAustin420](https://i.imgur.com/v7c1kEZ.gif)
